language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'

before_install:
  - sudo apt-get install -y --force-yes php5-ldap
  - php -m
  - echo "extension = ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - php -m

install:
  - composer update
